pub mod dav_fallback;
pub mod http_get_head;
#[cfg(feature = "native-http")]
pub mod native_http_delete;
#[cfg(feature = "native-http")]
pub mod native_http_options;
#[cfg(feature = "native-http")]
pub mod native_http_put;
#[cfg(feature = "native-locks")]
pub mod native_locks;
#[cfg(feature = "native-webdav")]
pub mod native_webdav_copy_move;
#[cfg(feature = "native-webdav")]
pub mod native_webdav_mkcol;
#[cfg(feature = "native-webdav")]
pub mod native_webdav_propfind;
#[cfg(feature = "native-webdav")]
pub mod native_webdav_proppatch;
